service: fst-api-dev

volumes:
  - /var/lib/fst/dev-data:/data

registry:
  server: ghcr.io
  username: focus-digital
  password:
    - REGISTRY_PASSWORD

env:
  clear:
    TENANT_ID: dev
    ALLOWED_ORIGIN: "https://fst-dev.focus-labs.io"

proxy:
  host: fst-dev-api.focus-labs.io
