service: pa-compact-demo-api

volumes:
  - /var/lib/fst/pa-compact-demo-data:/data

registry:
  server: ghcr.io
  username: focus-digital
  password:
    - REGISTRY_PASSWORD

env:
  clear:
    TENANT_ID: demo
    ALLOWED_ORIGIN: "https://pa-compact-demo.focus-labs.io"
    DEMO_MODE: true

proxy:
  host: pa-compact-demo-api.focus-labs.io
